"""Official Python SDK for the Krun API."""

import logging as _logging

from ._client import AsyncKrun, Krun
from ._constants import API_VERSION, DEFAULT_BASE_URL, DEFAULT_MAX_RETRIES, DEFAULT_TIMEOUT
from ._exceptions import (
    APIConnectionError,
    APIError,
    APIResponseValidationError,
    APITimeoutError,
    AuthenticationError,
    ConflictError,
    InferenceFailedError,
    InsufficientCreditsError,
    InternalServerError,
    InvalidRequestError,
    KrunError,
    NotFoundError,
    PermissionDeniedError,
    QuotaExceededError,
    RateLimitError,
    ServiceUnavailableError,
    UpstreamTimeoutError,
)
from ._version import __version__
from .types import (
    AbstentionStatus,
    Answer,
    ChoiceAnswer,
    ChoiceQuestion,
    ChoiceQuestionParam,
    DecisionResult,
    ExpectedParam,
    Feedback,
    Model,
    NoulAnswer,
    NoulQuestion,
    NoulQuestionParam,
    QuestionParam,
    QuestionsParam,
    QuestionType,
    ScoreAnswer,
    ScoreQuestion,
    ScoreQuestionParam,
    TaskType,
    Usage,
)

# Silent by default: the SDK never configures logging. Enable with logging.getLogger("krun").setLevel(DEBUG).
_logging.getLogger("krun").addHandler(_logging.NullHandler())

__all__ = [
    "API_VERSION",
    "DEFAULT_BASE_URL",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_TIMEOUT",
    "APIConnectionError",
    "APIError",
    "APIResponseValidationError",
    "APITimeoutError",
    "AbstentionStatus",
    "Answer",
    "AsyncKrun",
    "AuthenticationError",
    "ChoiceAnswer",
    "ChoiceQuestion",
    "ChoiceQuestionParam",
    "ConflictError",
    "DecisionResult",
    "ExpectedParam",
    "Feedback",
    "InferenceFailedError",
    "InsufficientCreditsError",
    "InternalServerError",
    "InvalidRequestError",
    "Krun",
    "KrunError",
    "Model",
    "NotFoundError",
    "NoulAnswer",
    "NoulQuestion",
    "NoulQuestionParam",
    "PermissionDeniedError",
    "QuestionParam",
    "QuestionType",
    "QuestionsParam",
    "QuotaExceededError",
    "RateLimitError",
    "ScoreAnswer",
    "ScoreQuestion",
    "ScoreQuestionParam",
    "ServiceUnavailableError",
    "TaskType",
    "UpstreamTimeoutError",
    "Usage",
    "__version__",
]
