"""Official Python SDK for the Krun API."""

import logging as _logging

from ._client import AssetFile, Assets, AsyncAssets, AsyncKrun, Krun
from ._constants import API_VERSION, DEFAULT_BASE_URL, DEFAULT_MAX_RETRIES, DEFAULT_TIMEOUT
from ._exceptions import (
    APIConnectionError,
    APIError,
    APIResponseValidationError,
    APITimeoutError,
    AuthenticationError,
    ConflictError,
    InferenceFailedError,
    InsufficientCreditsError,
    InternalServerError,
    InvalidRequestError,
    KrunError,
    NotFoundError,
    PermissionDeniedError,
    QuotaExceededError,
    RateLimitError,
    ServiceUnavailableError,
    UpstreamTimeoutError,
)
from ._version import __version__
from .types import (
    AbstentionStatus,
    Answer,
    Asset,
    AudioPart,
    AudioPartParam,
    ChoiceAnswer,
    ChoiceQuestion,
    ChoiceQuestionParam,
    ContentPart,
    ContentPartParam,
    ContextParam,
    DecisionResult,
    DeletedAsset,
    DocumentPart,
    DocumentPartParam,
    ExpectedParam,
    Feedback,
    ImagePart,
    ImagePartParam,
    Model,
    MultiAnswer,
    MultiQuestion,
    MultiQuestionParam,
    NoulAnswer,
    NoulQuestion,
    NoulQuestionParam,
    QuestionParam,
    QuestionsParam,
    QuestionType,
    ScoreAnswer,
    ScoreQuestion,
    ScoreQuestionParam,
    TaskType,
    TextPart,
    TextPartParam,
    Usage,
)

# Silent by default: the SDK never configures logging. Enable with logging.getLogger("krun").setLevel(DEBUG).
_logging.getLogger("krun").addHandler(_logging.NullHandler())

__all__ = [
    "API_VERSION",
    "DEFAULT_BASE_URL",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_TIMEOUT",
    "APIConnectionError",
    "APIError",
    "APIResponseValidationError",
    "APITimeoutError",
    "AbstentionStatus",
    "Answer",
    "Asset",
    "AssetFile",
    "Assets",
    "AsyncAssets",
    "AsyncKrun",
    "AudioPart",
    "AudioPartParam",
    "AuthenticationError",
    "ChoiceAnswer",
    "ChoiceQuestion",
    "ChoiceQuestionParam",
    "ConflictError",
    "ContentPart",
    "ContentPartParam",
    "ContextParam",
    "DecisionResult",
    "DeletedAsset",
    "DocumentPart",
    "DocumentPartParam",
    "ExpectedParam",
    "Feedback",
    "ImagePart",
    "ImagePartParam",
    "InferenceFailedError",
    "InsufficientCreditsError",
    "InternalServerError",
    "InvalidRequestError",
    "Krun",
    "KrunError",
    "Model",
    "MultiAnswer",
    "MultiQuestion",
    "MultiQuestionParam",
    "NotFoundError",
    "NoulAnswer",
    "NoulQuestion",
    "NoulQuestionParam",
    "PermissionDeniedError",
    "QuestionParam",
    "QuestionType",
    "QuestionsParam",
    "QuotaExceededError",
    "RateLimitError",
    "ScoreAnswer",
    "ScoreQuestion",
    "ScoreQuestionParam",
    "ServiceUnavailableError",
    "TaskType",
    "TextPart",
    "TextPartParam",
    "UpstreamTimeoutError",
    "Usage",
    "__version__",
]
